### ISSUE TITLE
Link to training data on README is 404ing

### ISSUE THREAD

**Issue by kyledrake** [cpuguy96/StepCOVNet#7]
https://drive.google.com/open?id=1eCRYSf2qnbsSOzC-KmxPWcSbMzi1fLHi

**Comment by kyledrake** [comment]
Any chance you could re-upload this quickly? Would be nice to get access to this.

**Comment by cpuguy96** [comment]
Pretty much we need to re-create the training data from the raw data stored in Google Drive. The raw data is preprocessed using [SMDataTools](https://github.com/jhaco/SMDataTools) to find audio and text data. Then ,the README should be updated with a new link to the input data.

@jhaco is going to work on this.

**Comment by jhaco** [comment]
I'm going to also playtest and prune some of the raw data. Will need to order an external 4-key pad, so give me about 2 weeks. I'll post a changelog detailing reasons for some of the removals.

**Comment by jhaco** [comment]
Update: finally got the little doodad to play Stepmania with. Downloaded 7.5 GBs worth of raw data that we had in the drive, wrote a nasty little script that snaps all songs with multiple BPMs out of existence, and my songs to playtest went from 618 down to 241.

Very cool. I'm going to try shaving off 41 off the remaining songs and then create the training data and upload a new drive...probably by next week.

**Comment by trinca95** [comment]
Speaking about the training, it's really slow when i tried it, on 90 full songs was asking for like 10days of my cpu(i7 9700k)... i didn't check for time constrains but it seems strange.

**Comment by D-Vaillant** [comment]
Hi, any update on this? I'm possibly going to have to retrain the model myself (because the pretrained model isn't working for me) and if it's possible to not have to curate the dataset myself that'd be nice.

**Comment by jhaco** [comment]
Update from last I left off: I had playtested 101/241 songs and was able to remove 39 songs of low quality play imo. I now have a manageable 202 songs to work with (from an initial total of 618 lol). Ideally, I'd like to play and prune the rest of the songs so we'd have a higher possibility of generating "satisfying to play" songs, but not enough time lately.

I'll try and find time to work with @cpuguy96 and push for a working build so we all can train our own models. Never tried personally running this project on my laptop tbh (I don't have a desktop)...hopefully it doesn't set it on fire.

**Comment by cpuguy96** [comment]
@D-Vaillant Sorry for the delay. 

@jhaco has uploaded the training data and I updated the README to the correct link:
https://drive.google.com/drive/folders/1RNKLXfwTEFdGMCct5bhgIApoNG-8Zg79?usp=drive_link

@D-Vaillant Can you confirm that the link works and you are can see the data?

**Comment by D-Vaillant** [comment]
Yup, works for me.
